import Head from 'next/head'
import Header from '../components/header/Header';
function projects() {
    return (
        <>
            <Head>
                <title>My Portfolio CV</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>	
            <Header>						
            </Header>           
            
        </>
      )
}

export default projects;
